companymanagement/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^personalia/',include('personalia.urls')),
    url(r'^training/',include('training.urls')),
]

personalia/urls.py
from django.conf.urls import url
from . import views

app_name = 'personalia'
urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^menu/(?P<menu_id>[0-9]+)/$',views.menuShow, name='menuShow'),
    url(r'^action/(?P<action_id>[0-9]+)/(?P<params>[0-9]+)/$',views.actionShow, name='actionShow'),
]

training/urls.py
from django.conf.urls import url
from . import views

app_name = 'training'
urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^menu/(?P<menu_id>[0-9]+)/$',views.menuShow, name='menuShow'),
    url(r'^action/(?P<action_id>[0-9]+)/(?P<params>[0-9]+)/$',views.actionShow, name='actionShow'),
]

personalia/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
from django.db import models

class MenuManager(models.Manager):
    def get_queryset(self):
        return super(MenuManager,
            self).get_queryset().filter(is_active=True)

class Menu(models.Model):
    MENUTYPE_CHOICE = [
        ('g','Group'),('p','Page'),
    ]

    menu_id = models.CharField(max_length=6,primary_key=True)
    menu_parent = models.CharField(max_length=6,default='000000')
    menu_type = models.CharField(max_length=1,
        choices=MENUTYPE_CHOICE,default='g'
    )
    menu_name = models.CharField(max_length=250,default='menu')
    slug = models.SlugField(max_length=250,
        unique=menu_id,blank=True)
    is_active = models.BooleanField(default=True)
    is_act_view = models.BooleanField(default=True)
    menu_order = models.IntegerField()
    templatesource = models.CharField(max_length=250,default='personalia/index.html')
    query_function = models.CharField(max_length=20,default='GetIndex')

    objects = models.Manager()
    menu_show = MenuManager()

    class Meta:
        ordering = ('menu_parent','menu_order',)

    def __str__(self):
        return self.menu_name

class Action(models.Model):
    menu_id = models.ForeignKey(Menu, related_name='actionMenu', on_delete=models.CASCADE)
    action_name = models.CharField(max_length=250,default='action')
    action_header = models.CharField(max_length=250,default='action')
    slug = models.SlugField(max_length=250,
        unique=id,blank=True)
    is_enable = models.BooleanField(default=True)
    action_order = models.IntegerField()
    templatesource = models.CharField(max_length=250,default='personalia/index.html')
    query_function = models.CharField(max_length=20,default='GetIndex')
    is_direct = models.BooleanField(default=True)

    class Meta:
        ordering = ('menu_id','action_order',)

    def __str__(self):
        return self.action_name

class Person(models.Model):
    GRADUATE_CHOICE = [
        ('1','SD'),('2','SMP'),('3','SMA'),('4','D3'),('5','S1'),
    ]
    GENDER_CHOICES = [
        ('L','Laki-laki'),('P','Perempuan'),
    ]
    STATUS_CHOICES = [
        ('1','Lajang'),('2','Menikah'),('3','Janda/Duda'),
    ]

    name = models.CharField(max_length=50)
    birthplace = models.CharField(max_length=50,blank=True,null=True)
    birth = models.DateField(blank=True,null=True)#(help_text='format is mm/dd/yyyy exmp:02/28/2000')
    gender = models.CharField(max_length=1,choices=GENDER_CHOICES)
    address = models.TextField(max_length=200,blank=True,null=True)
    status = models.CharField(max_length=1,choices=STATUS_CHOICES,blank=True,null=True)
    school = models.CharField(max_length=50,blank=True,null=True)
    graduate = models.CharField(max_length=3,
        choices=GRADUATE_CHOICE,blank=True,null=True)
    mobilephone = models.CharField(max_length=15,blank=True,null=True)
    bbm = models.CharField(max_length=8,blank=True,null=True)
    email = models.EmailField(max_length=50,blank=True,null=True)

    class Meta:
        ordering = ('gender','name','birth',)
        #unique_together = ('name','birthplace','birth','gender','email',)

    def __str__(self): # __unicode__ on Python 2
        #return '{}-{}'.format(str(self.id),self.name)
        return '{} {}'.format(str(self.id),self.name)

class Leader(models.Model):
    MANAGER_CHOICES = [
        ('ahm','ahmad'),('ksm','kusmawan'),('mgd','migud'),
        ('sdk','sodikin'),('sdr','sodirun'),
    ]

    leader_id = models.CharField(max_length=5,primary_key=True,)
    name = models.CharField(max_length=50)
    manager = models.CharField(max_length=5,choices=MANAGER_CHOICES)

    class Meta:
        ordering = ('manager','leader_id',)

    def __str__(self):
        return self.name

class EmployeeReport(models.Manager):
    def Emp(self,condition):
        from django.db import connection as con
        with con.cursor() as cursor:
            cursor.execute('''
                select e.grade,p.gender,count(p.id) as counter
                from personalia_employee e
                inner join personalia_person p on e.person_id = p.id
                where %s
                group by e.grade,p.gender
                order by e.grade
            ''' % (condition,))
            result_list = []
            for row in cursor.fetchall():
                result_list.append(row)
        return result_list

class Employee(models.Model):
    LEVEL_CHOICES = [
        ('0','WB'),('1','Pra A1'),('2','A1_1'),('3','A1_2'),('4','A1_3'),('5','A2_a'),
        ('6','A2_b'),
    ]

    SA_CHOICES = [
        ('ak','AK'),('pa','PA'),('bk1','BK_1'),('bk2','BK_2'),('bk3','BK_3')
    ]
    person = models.OneToOneField(
        Person,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    grade = models.CharField(max_length=1,
        choices=LEVEL_CHOICES)
    date_register = models.DateField(blank=True,null=True)
    status_active = models.CharField(max_length=5,choices=SA_CHOICES)
    leader = models.ForeignKey(Leader, related_name='LeaderOf')
    description = models.TextField(max_length=500,blank=True,null=True)
    date_input = models.DateTimeField(default=timezone.now)

    objects = models.Manager()
    emp_report = EmployeeReport()

    class Meta:
        ordering = ('status_active','grade','person',)

    def __str__(self): # __unicode__ on Python 2
        return '{}'.format(self.person)

class Report(models.Model):
    report_name = models.CharField(max_length=200)
    script_name = models.CharField(max_length=200)
    group_report = models.CharField(max_length=10)
    is_enable = models.BooleanField(default=True)

    class Meta:
        ordering = ('report_name',)

class Coaching(models.Model):
    employee = models.ForeignKey(Employee, related_name='empOf')
    course = models.CharField(max_length=100)
    date_coaching = models.DateTimeField(default=timezone.now)
    description = models.TextField(max_length=500,blank=True,null=True)

    class Meta:
        ordering = ('id',)

class ErrorUpload(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500,blank=True,null=True)
    date_input = models.DateTimeField(default=timezone.now)

personalia/forms.py
from django import forms
from .models import Person,Employee,Coaching
from django.utils.translation import ugettext_lazy as _

class DateInput(forms.DateInput):
    input_type = 'date'

class fEmployee(forms.ModelForm):
    class Meta:
        model = Employee
        exclude = ['person','date_input',]
        widgets = {
            'date_register':DateInput(),
        }
        labels = {
            'grade': _('Level'),
            'date_register': _('Tanggal Daftar'),
            'status_active': _('Status'),
            'description': _('Keterangan'),
        }

class fPerson(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'
        widgets = {
            'birth':DateInput(),
        }
        labels = {
            'name': _('Nama'),
            'birthplace': _('Tempat Lahir'),
            'birth': _('Tanggal Lahir'),
            'gender': _('Jenis Kelamin'),
            'address': _('Alamat'),
            'status': _('Status Pernikahan'),
            'school': _('Sekolah'),
            'graduate': _('Jenjang Pendidikan'),
            'mobilephone': _('Handphone'),
        }

class fCoaching(forms.ModelForm):
    class Meta:
        model = Coaching
        exclude = ['employee']
        widgets = {
            'date_coaching':DateInput(),
        }
        labels = {
            'course':_('Materi Pelatihan'),
            'date_coaching':_('Tanggal Pelatihan'),
            'description':_('Keterangan'),
        }

class fUplEmp(forms.Form):
    file_upload = forms.FileField()

personalia/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render,get_object_or_404
from .models import Menu,Action
from personalia.views_script import index,employees,leader,report,\
    coaching
from django.http import HttpResponse
from datetime import datetime

query = {
    'GetIndex':index.GetIndex,
    'GetEmloyees':employees.GetEmloyees,
    'newEmp':employees,
    'editEmp':employees,
    'uplEmp':employees,
    'GetLeader':leader.GetLeader,
    'GetReport':report.GetEmpReport,
    'GetEmpReport':report,
    'GetCoaching':coaching.GetCoaching,
    'newCoach':coaching,
    'GetCoarchReport':coaching,
}

def index(request):
    return render(request,'personalia/index.html')

def menuShow(request,menu_id):
    menu = Menu.objects.get(pk=menu_id)
    action = Action.objects.all().filter(menu_id=menu.menu_id,is_enable=True)
    variable = query[menu.query_function]()
    return render(request,menu.templatesource,{
        'variable' : variable,'menu' : menu,'action' : action,
    })

def actionShow(request,action_id,params):
    action = Action.objects.get(pk=action_id)
    params = {'action':action,'params':params}
    #raise Exception,action.query_function
    context = query[action.query_function].GetContext(request,params)
    if action.is_direct :
        date_now = datetime.today().strftime("%d%m%y %H:%M:%S")
        response = HttpResponse(content_type='application/ms-excel')
        response['Content-Disposition'] = 'attachment; filename="%s %s.xlsx"' % (
            context['report_name'],date_now,)
        response = query[action.query_function].ConstructReport(response,context)
        return response
    else :
        return render(request,action.templatesource,context)

personalia/templates/personalia/coaching.html
{% extends "base.html" %}
{% block title %}Employee Data{% endblock %}
{% block value %}
  <div id="employee-data">
    <h2>{{menu.menu_name}}</h2><br>
  {% if variable %}
    <table>
      <tr>
        <th>Nama Karyawan</th>
        <th>Level</th>
        <th>Grup</th>
      </tr>
    {% for p in variable.employee %}
      <tr>
        <td>
          <a href="{% url 'personalia:actionShow' variable.action_id p.person_id %}">
            {{p.person.name|upper}}
          </a>
        </td>
        <td>{{p.get_grade_display}}</td>
        <td>{{p.leader.leader_id}}</td>
      </tr>
    {% endfor %}
      <tr>
        <td colspan="2">{{variable.total|title}}</td>
        <td>{{variable.count}}</td>
      </tr>
    </table>
  {% endif %}
  </div>
{% endblock value %}

personalia/templates/personalia/employees.html
{% extends "base.html" %}
{% block title %}Employee Data{% endblock %}
{% block value %}
  <div id="employee-data">
    <h2>{{menu.menu_name}}</h2><br>
  {% if variable %}
    <table>
      <tr>
        <th>Nama</th>
        <th>Jenis Kelamin</th>
        <th>Status Pernikahan</th>
        <th>Level</th>
      </tr>
    {% for p in variable.employee %}
      <tr>
        <td>
          <a href="{% url 'personalia:actionShow' variable.action_id p.person_id %}">
            {{p.person.name|upper}}
          </a>
        </td>
        <td>{{p.person.get_gender_display}}</td>
        <td>{{p.person.get_status_display}}</td>
        <td>{{p.get_grade_display}}</td>
      </tr>
    {% endfor %}
      <tr>
        <td colspan="3">{{variable.total|title}}</td>
        <td>{{variable.count}}</td>
      </tr>
    </table>
  {% endif %}
  </div>
{% endblock value %}

personalia/templates/personalia/f_coaching.html
{% extends "base.html" %}
{% block title %}Input Form{% endblock %}
{% block value %}
  <h4>{{action.action_header|title}}</h4>
  <h5>({{emp.person.name}} {{emp.get_grade_display}} {{emp.leader.leader_id}})</h5>
  <hr>
  {% if msg %}
    <h4>----{{msg}}----</h4>
  {% endif %}

  <form action="." method="post">
    {% for f in form %}
      {{f.as_p}}
    {% endfor %}
    {% csrf_token %}
    {% for b in button %}
      <input type="submit" value="{{ b }}">
    {% endfor %}
  </form>
  <br>
  <h4>Data Pelatihan</h4><hr>
  <table>
    <tr>
      <th>Materi Pelatihan</th>
      <th>Tanggal Pelatihan</th>
      <th>Keterangan</th>
    </tr>
  {% for c in coachHist %}
    <tr>
      <td>
        {{c.course|title}}
      </td>
      <td>{{c.date_coaching|date:"d F Y H:i"}}</td>
      <td>{{c.description}}</td>
    </tr>
  {% endfor %}
    <tr>
      <td colspan="2">{{variable.total|title}}</td>
      <td>{{variable.count}}</td>
    </tr>
  </table>
  <br>
  <div id="btnExport">
    <a href="{% url 'personalia:actionShow' action_id emp.person.id %}">
      Export Excel
    </a>
  </div>
{% endblock %}

personalia/templates/personalia/form.html
{% extends "base.html" %}
{% block title %}Input Form{% endblock %}
{% block value %}
  <h4>{{action.action_header|title}}</h4>
  <hr>
  {% if msg %}
    <h4>----{{msg}}----</h4>
  {% endif %}

  <form action="." method="post" enctype="multipart/form-data">
    {% for f in form %}
      {{f.as_p}}
    {% endfor %}
    {% csrf_token %}
    {% comment %}
            {{dateform}}
    {% endcomment %}
    {% for b in button %}
      <input type="submit" value="{{ b }}">
    {% endfor %}
  </form>
{% endblock %}

personalia/templates/personalia/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}
{% block value %}
  <h1>Welcome</h1>
  <p>
    Application employees are present to facilitate you in managing employee data.
    With this application you can manage employee data (<i>Create, New, Update, Delete</i>)
    Example : employee data, report, etc.
  </p>
  <p>
    Please select menus at the left side.
  </p>
  <p>
    If there are suggestions and criticisms regarding this application, please send your comments and suggestions via e-mail <a href="#">sodikinsadani@gmail.com</a>.
  </p>
{% endblock %}

personalia/templates/personalia/leader.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}
{% block value %}
  <h1>Welcome</h1>
  <p>
    Application employees are present to facilitate you in managing employee data.
    With this application you can manage employee data (<i>Create, New, Update, Delete</i>)
    Example : employee data, report, etc.
  </p>
  <p>
    Please select menus at the left side.
  </p>
  <p>
    If there are suggestions and criticisms regarding this application, please send your comments and suggestions via e-mail <a href="#">sodikinsadani@gmail.com</a>.
  </p>
{% endblock %}

personalia/templates/personalia/menu.html
<ul>
  {% for m in menu_list %}
    {% if m.menu_type == 'g' %}
      <li>
        <a href="{% url 'personalia:menuShow' m.menu_id %}">{{m.menu_name|title}}</a>
        {% for sm in menu_list %}
            {% if sm.menu_parent == m.menu_id %}
                <ul>
                  <li>
                    <a href="{% url 'personalia:menuShow' sm.menu_id %}">{{sm.menu_name|title}}</a>
                  </li>
                </ul>
            {% endif %}
        {% endfor %}
      </li>
    {% endif %}
  {% endfor %}
</ul>

personalia/templates/personalia/report.html
{% extends "base.html" %}
{% block title %}Laporan Karyawan{% endblock %}
{% block value %}
  <div id="repot">
    <h1>{{menu|title}}</h1>
    {% if variable %}
      <table>
        <tr>
          <th>Report Name</th>
          <th>Action</th>
        </tr>
      {% for r in variable.report %}
        <tr>
          <td>{{r.report_name|title}}</td>
          <td>
            <a href="{% url 'personalia:actionShow' variable.action_id r.id %}">
              Download
            </a>
          </td>
        </tr>
      {% endfor %}
      </table>
    {% endif %}
  </div>
{% endblock value %}